# Generated by Django 3.0.8 on 2021-02-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('registration_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('alert_code', models.IntegerField(primary_key=True, serialize=False)),
                ('alerte_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=8)),
                ('street_name', models.CharField(max_length=50)),
                ('street_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PoliceStation')),
            ],
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Agent')),
                ('connected_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ConnectedAssistant')),
                ('wello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Wello')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_nature', models.CharField(max_length=20)),
                ('detected_at', models.DateTimeField(auto_now=True)),
                ('seen_by_agent', models.BooleanField(default=False)),
                ('confirmed_by_agent', models.BooleanField(default=False)),
                ('message_sent', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patrol')),
            ],
        ),
    ]
