# Generated by Django 3.0.8 on 2021-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patrol_listening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrol',
            name='listening',
        ),
        migrations.AddField(
            model_name='connectedassistant',
            name='listenning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectedassistant',
            name='turn_on',
            field=models.BooleanField(default=False),
        ),
    ]
