# Generated by Django 3.0.8 on 2021-02-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210214_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='fake_positive',
            field=models.BooleanField(default=False),
        ),
    ]
