# Generated by Django 3.0.8 on 2021-02-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210214_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerttemplate',
            old_name='alerte_message',
            new_name='alert_message',
        ),
    ]
